### ISSUE TITLE
无法识别HA安装的播放器

### ISSUE THREAD

**Issue by WinkeyLin** [shaonianzhentan/cloud_music#1]
Hassio0.103.2已安装Vlc和Kodi，但是插件依然报错检测到HA中没有安装播放器。请问在configuration.yaml中的media_player项除了ha_cloud_music还要把系统播放器加进去吗？

**Comment by shaonianzhentan** [comment]
你需要在media_player配置你需要的播放器，并且要放在ha_cloud_music的前面
```
# 示例
media_player:
  - platform: vlc
  - platform: dlna_dmr
    url: http://192.168.1.100:49494/description.xml
  - platform: ha_cloud_music

```
