### ISSUE TITLE
VLC telnet 下的若干错误

### ISSUE THREAD

**Issue by Erimus-Koo** [shaonianzhentan/cloud_music#2]
# 使用环境
- hass运行在mac上，vlc运行在一台局域网内的机器上，通过vlc telnet连接。
- in hass
```
media_player:
  - platform: vlc_telnet
    name: VLC Player
    host: 10.0.0.13
    port: 4212
    password: myvlc
  - platform: ha_cloud_music
    api_url: http://localhost:3000
```
- 操作在mac端safari浏览器，桌面模式。

# 错误信息
- vlc的播放进度和网页不一致。
- 网页拖动进度条无效。
- 歌曲结束网页播放时间会过头，且不会自动切歌。
- 结束后因为还在播放状态，播放按钮的状态就还是暂停。但是点击的话，是从头播放。
- 总之好像都是围绕着进度条来的，可能 vlc telnet 也得不到进度条？

# 附 telnet 设置
- vlc播放器内，ctrl+P打开设置
- 点左下角显示设置/全部
- 界面/主界面>勾选telnet
- 界面/主界面/lua>lua telnet/密码（这里必须设一个密码，比如myvlc，不然hass里会报无密码，没试过留空。）

---

# 额外问题
- 现在是不是只能以访客身份获得自己公开的专辑等等？
- 那个 node js 版的倒是支持 api，我看是支持日推和私人FM。
- 另外这个播放器的原理是什么？会用到本地缓存嘛？有的话请问在什么目录？
